title: Leeds 2023 twitter Summary Statistics
data-files-label: service
data-file:
  twitter:
    path: data\metrics\social\twitter.csv
    metrics: &metrics
    - audience_last
    - engagements_total
    - net_audience_growth_total
    filter-range: &filter 2022-01-01:2022-12-31
    filter-col: &filter_col_name date
  facebook:
    path: data\metrics\social\facebook.csv
    metrics: *metrics
    filter-range: *filter
    filter-col: *col_name
  instagram:
    path: data\metrics\social\instagram.csv
    metrics: *metrics
    filter-range: *filter
    filter-col: *col_name
  linkedin:
    path: data\metrics\social\linkedin.csv
    metrics: *metrics
    filter-range: *filter
    filter-col: *col_name