title: My World My City My neighbourhood Summary Metrics
data_files_label: file
data_file:
  projects:
    path: data\reference\mwmcmn\mwmcmn_ace.csv
    metrics:
      - Artist_ID_count
      - Sponsored_Artists_Days_total
      - Other_Artists_Employed_Days_total
      - Performance_Or_Exhibition_Days_total
      - Sessions_For_Education_Training_Or_Participation_total
      - Artists_Employed_total
      - Participants_total
      - Live_Audience_total
      - Online_Audience_total
    fillna: 0
    to_int:
  survey:
    path: data\reference\mwmcmn\mwmcmn_lcf.csv
    metrics:
      - Benefited_Total_total
      - Benefited_0_4_total
      - Benefited_5_12_total
      - Benefited_13_18_total
      - Benefited_19_25_total
      - Benefited_Unknown_total
      - Q1_total
      - Q2_total
      - Q3_total
      - Q4_total
      - Q5_total
      - Q6_total
      - Q7_total
      - Q8_total
      - Q9_total
      - Q10_total
      - Q11_total
    fillna: 0
    to_int:
      