stages:
  transform:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/media/transform_cision.py
    wdir: ../../..
    deps:
    - scripts/metrics/media/transform_cision.py
    - scripts/metrics/media/cision.py
    - working/manual/media/
    outs:
    - data/metrics/media_coverage/combined_cision.csv:
        persist: true
        cache: false
  transform_historic:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/media/combine_historic.py
    wdir: ../../..
    deps:
    - scripts/metrics/media/combine_historic.py
    - working/manual/media/
    outs:
    - data/metrics/media_coverage/combined_historic.csv:
        persist: false
        cache: false
  prepare:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/media/process.py
    wdir: ../../..
    deps:
    - scripts/metrics/media/process.py
    - data/metrics/media_coverage/combined_cision.csv
    - data/metrics/media_coverage/combined_historic.csv
    outs:
    - docs/metrics/media_coverage/_data/outlet_count.csv:
        cache: false
    - docs/metrics/media_coverage/_data/medium_count.csv:
        cache: false
    - docs/metrics/media_coverage/_data/monthly_count.csv:
        cache: false
