stages:
  ref-postcodes:
    cmd: PYTHONPATH=scripts python3 scripts/reference_data/postcodes.py working/ref/onspd-extract.csv
    deps:
    - scripts/reference_data/postcodes.py
    - working/ref/onspd-extract.csv