# Callouts pipelines
stages:
  extract:
    cmd: PYTHONPATH=. python3 scripts/metrics/promote-events/extract.py
    wdir: ../../..
    always_changed: true
    deps:
      - scripts/metrics/promote-events/extract.py
    outs:
      - working/metrics/promote-events/:
          persist: false
          cache: false
  transform:
    cmd: PYTHONPATH=. python3 scripts/metrics/promote-events/transform.py
    wdir: ../../..
    deps:
      - scripts/metrics/promote-events/transform.py
      - working/metrics/promote-events/
    outs:
      - data/metrics/events/promote-events/events.csv:
          persist: false
          cache: false
  prepare:
    cmd: PYTHONPATH=. python3 scripts/metrics/promote-events/prepare.py
    wdir: ../../..
    deps:
      - scripts/metrics/promote-events/prepare.py
      - data/metrics/events/promote-events/events.csv
    outs:
      - docs/metrics/events/promote/_data/headline.json:
          persist: true
          cache: false
      - docs/metrics/events/promote/_data/by_ward.csv:
          persist: true
          cache: false
      - docs/metrics/events/promote/_data/by_month.csv:
          persist: true
          cache: false
