# Callouts pipelines
stages:
  extract:
    frozen: false
    cmd: PYTHONPATH=scripts python3 scripts/metrics/events/awakening/extract.py
    wdir: ../../../..
    always_changed: true
    deps:
    - scripts/metrics/events/awakening/extract.py
    outs:
    - working/ballot/:
        persist: true
        cache: false
  transform:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/events/awakening/process.py
    wdir: ../../../..
    deps:
    - scripts/metrics/events/awakening/process.py
    - data/reference/postcodes.csv
    - working/ballot/individual_ballots.csv
    - working/ballot/group_ballots.csv
    outs:
    - data/metrics/ballot/ballot_entries.csv:
        persist: true
        cache: false
    - data/metrics/ballot/ballot_group_entries.csv:
        persist: true
        cache: false
  transform_attendees:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/events/awakening/transform_attendees.py
    wdir: ../../../..
    deps:
      - scripts/metrics/events/awakening/transform_attendees.py
      - working/manual/events/Awakening/
    outs:
    - data/metrics/events/awakening/attendees.csv:
        persist: true
        cache: false
  prepare:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/events/awakening/summarize.py
    wdir: ../../../..
    deps:
    - scripts/metrics/events/awakening/summarize.py
    - data/metrics/ballot/
    outs:
    - docs/metrics/events/awakening/_data/by_age.csv:
        cache: false
    - docs/metrics/events/awakening/_data/by_date.csv:
        cache: false
    - docs/metrics/events/awakening/_data/by_local_authority.csv:
        cache: false
    - docs/metrics/events/awakening/_data/by_source.csv:
        cache: false
    - docs/metrics/events/awakening/_data/by_ward.csv:
        cache: false
    - docs/metrics/events/awakening/_data/current.json:
        cache: false
    - docs/metrics/events/awakening/_data/local_autority_stats.json:
        cache: false
  prepare_attendees:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/events/awakening/prepare_attendees.py
    wdir: ../../../..
    deps:
      - scripts/metrics/events/awakening/prepare_attendees.py
      - data/metrics/events/awakening/attendees.csv
    outs:
      - docs/metrics/events/awakening/_data/attendees.json:
          cache: false
      - docs/metrics/events/awakening/_data/attendees_by_ward.csv:
          cache: false
      - docs/metrics/events/awakening/_data/attendees_by_la.csv:
          cache: false