# Callouts pipelines
stages:
  extract:
    frozen: false
    cmd: PYTHONPATH=scripts python3 scripts/metrics/ballot/extract.py
    wdir: ../../..
    always_changed: true
    deps:
    - scripts/metrics/ballot/process.py
    - data/reference/postcodes.csv
    outs:
    - working/ballot/:
        persist: true
        cache: false
  transform:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/ballot/process.py
    wdir: ../../..
    deps:
    - scripts/metrics/ballot/process.py
    - data/reference/postcodes.csv
    - working/ballot/
    outs:
    - data/metrics/ballot/ballot_entries.csv:
        persist: true
        cache: false
    - data/metrics/ballot/ballot_group_entries.csv:
        persist: true
        cache: false
  transform_attendees:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/ballot/transform_attendees.py
    wdir: ../../..
    deps:
      - working/manual/events/Awakening/
    outs:
    - data/metrics/events/awakening/attendees.csv:
        persist: true
        cache: false
  prepare:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/ballot/summarize.py
    wdir: ../../..
    deps:
    - scripts/metrics/ballot/summarize.py
    - data/metrics/ballot/
    outs:
    - docs/metrics/events/awakening/_data/by_age.csv:
        cache: false
    - docs/metrics/events/awakening/_data/by_date.csv:
        cache: false
    - docs/metrics/events/awakening/_data/by_local_authority.csv:
        cache: false
    - docs/metrics/events/awakening/_data/by_source.csv:
        cache: false
    - docs/metrics/events/awakening/_data/by_ward.csv:
        cache: false
    - docs/metrics/events/awakening/_data/current.json:
        cache: false
    - docs/metrics/events/awakening/_data/local_autority_stats.json:
        cache: false
