vars:
  - top: ../../../..
stages:
  extract:
    cmd: python3 extract.py
    deps:
      - extract.py
      - pipes.py
      - ${top}/lib/sources/ticket_tailor.py
    outs:
      - ${top}/working/metrics/ticketing/orders.csv:
          cache: false
  transform:
    cmd: papermill tickets.ipynb ${top}/working/output/tickets.ipynb
    deps:
      - tickets.ipynb
      - pipes.py
      - ${top}/working/metrics/ticketing/orders.csv
