vars:
  - top: ../../../..
stages:
  extract:
    cmd: python3 extract.py
    deps:
      - extract.py
      - pipes.py
      - ${top}/lib/sources/ticket_tailor.py
    outs:
      - ${top}/working/metrics/ticketing/orders.csv:
          cache: false
  transform:
    cmd: papermill tickets.ipynb ${top}/working/output/tickets-transform.ipynb
    deps:
      - tickets.ipynb
      - pipes.py
      - ${top}/working/metrics/ticketing/orders.csv
    outs:
      - ${top}/data/metrics/events/tickets/orders.csv:
          cache: false

  prepare:
    cmd: papermill prepare.ipynb ${top}/working/output/tickets-prepare.ipynb
    deps:
      - prepare.ipynb
      - ${top}/data/metrics/events/tickets/orders.csv
    outs:
      - ${top}/docs/metrics/tickets/_data/:
          cache: false
