# Callouts pipelines
stages:
  extract:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/callouts/extract.py
    wdir: ../../..
    always_changed: true
    deps:
    - scripts/metrics/callouts/extract.py
    outs:
    - working/metrics/callouts/:
        persist: false
        cache: false
  transform:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/callouts/transform.py
    wdir: ../../..
    deps:
    - scripts/metrics/callouts/transform.py
    - working/metrics/callouts/
    - data/reference/postcodes.csv
    outs:
    - data/metrics/callouts/:
        persist: false
        cache: false