# Callouts pipelines
stages:
  stage:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/callouts/stage.py
    wdir: ../../..
    always_changed: true
    deps:
    - scripts/metrics/callouts/stage.py
    outs:
    - working/metrics/callouts/:
        persist: true
        cache: false
  build:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/callouts/build.py
    wdir: ../../..
    deps:
    - scripts/metrics/callouts/build.py
    - working/metrics/callouts/
    - data/reference/postcodes.csv
    outs:
    - data/metrics/callouts/:
        persist: true
        cache: false