stages:
  postcodes:
    cmd: PYTHONPATH=scripts python3 scripts/reference_data/postcodes.py working/ref/onspd-extract.csv
    wdir: ../../
    deps:
    - scripts/reference_data/postcodes.py
    - working/ref/onspd-extract.csv
    outs:
    - data/reference/postcodes.csv:
        cache: false

