stages:
  # extract:
  #   cmd: dvc update working/metrics/rosterfy.dvc
  #   wdir: ../../..
  #   deps:
  #     - remote://oicloud/home/leeds2023/rosterfy/
  #   outs:
  #     - working/metrics/rosterfy/:
  #         persist: true
  #         cache: false
  transform:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/volunteers/transform.py
    wdir: ../../..
    deps:
    - scripts/metrics/volunteers/transform.py
    - working/manual/volunteers/volunteering-hours.csv
    - working/metrics/rosterfy/current-checkpoint.csv
    outs:
    - data/metrics/volunteers/shifts.csv:
        cache: false
        persist: true
    - data/metrics/volunteers/volunteers.csv:
        cache: false
        persist: true
    frozen: true
  prepare:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/volunteers/prepare.py
    wdir: ../../..
    deps:
    - scripts/metrics/volunteers/prepare.py
    - data/metrics/volunteers/volunteers.csv
    - data/metrics/volunteers/shifts.csv
    outs:
    - docs/metrics/volunteers/_data:
        persist: true
        cache: false
