stages:
  # extract:
  #   cmd: dvc update working/metrics/rosterfy.dvc
  #   wdir: ../../..
  #   deps:
  #     - remote://oicloud/home/leeds2023/rosterfy/
  #   outs:
  #     - working/metrics/rosterfy/:
  #         persist: true
  #         cache: false
  transform-signups:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/volunteers/transform_signups.py
    wdir: ../../..
    deps:
    - scripts/metrics/volunteers/transform_signups.py
    - scripts/metrics/volunteers/data.py
    - scripts/metrics/volunteers/metadata.py
    - scripts/metrics/volunteers/setup.py
    - scripts/metrics/volunteers/states.py
    - working/manual/volunteers/current-checkpoint.csv
    outs:
    - data/metrics/volunteers/volunteers.csv:
        cache: false
        persist: true
  transform-shifts:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/volunteers/transform_shifts.py
    wdir: ../../..
    deps:
    - scripts/metrics/volunteers/transform_shifts.py
    - working/manual/volunteers/volunteering-hours.csv
    outs:
    - data/metrics/volunteers/shifts.csv:
        cache: false
        persist: true
  prepare:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/volunteers/prepare.py
    wdir: ../../..
    deps:
    - scripts/metrics/volunteers/prepare.py
    - data/metrics/volunteers/volunteers.csv
    - data/metrics/volunteers/shifts.csv
    outs:
    - docs/metrics/volunteers/_data:
        persist: true
        cache: false
