stages:
  # extract:
  #   cmd: dvc update working/metrics/rosterfy.dvc
  #   wdir: ../../..
  #   deps:
  #     - remote://oicloud/home/leeds2023/rosterfy/
  #   outs:
  #     - working/metrics/rosterfy/:
  #         persist: true
  #         cache: false
  transform-signups:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/volunteers/transform_signups.py
    wdir: ../../..
    deps:
    - scripts/metrics/volunteers/transform_signups.py
    - scripts/metrics/volunteers/data.py
    - scripts/metrics/volunteers/metadata.py
    - scripts/metrics/volunteers/setup.py
    - scripts/metrics/volunteers/states.py
    - working/metrics/rosterfy/current-checkpoint.csv
    outs:
    - data/metrics/volunteers/volunteers.csv:
        cache: false
        persist: true
    - docs/metrics/volunteers/_data/metadata/volunteers.json:
        cache: false
  transform-shifts:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/volunteers/transform_shifts.py
    wdir: ../../..
    deps:
    - scripts/metrics/volunteers/transform_shifts.py
    - working/metrics/rosterfy/volunteering-hours.csv
    outs:
    - data/metrics/volunteers/shifts.csv:
        cache: false
        persist: true
  prepare:
    cmd: PYTHONPATH=scripts python3 scripts/metrics/volunteers/prepare.py
    wdir: ../../..
    deps:
    - scripts/metrics/volunteers/prepare.py
    - data/metrics/volunteers/volunteers.csv
    - data/metrics/volunteers/shifts.csv
    outs:
    - docs/metrics/volunteers/_data/by_ward.csv:
        cache: false
    - docs/metrics/volunteers/_data/by_week.csv:
        cache: false
    - docs/metrics/volunteers/_data/by_local_authority.csv:
        cache: false
    - docs/metrics/volunteers/_data/la_stats.json:
        cache: false
    - docs/metrics/volunteers/_data/west_yorkshire.csv:
        cache: false
    # Shift processing
    - docs/metrics/volunteers/_data/shifts/by_week.csv:
        cache: false
    - docs/metrics/volunteers/_data/shifts/summary.json:
        cache: false
