name: Data Pipeline

'on':
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup credentials file
        run: |
          mkdir credentials
          echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} | base64 -d > ./credentials/serviceAccountKey.json

      - name: Update data
        env:
          PYTHONPATH: scripts
          TYPEFORM_PRIVATE_TOKEN: ${{ secrets.TYPEFORM_PRIVATE_TOKEN }}
          OI_SFTP_HOST: ${{ secrets.OI_SFTP_HOST }}
          OI_SFTP_USERNAME: ${{ secrets.OI_SFTP_USERNAME }}
          OI_SFTP_PASSWORD: ${{ secrets.OI_SFTP_PASSWORD }}
          GOOGLE_APPLICATION_CREDENTIALS: './credentials/serviceAccountKey.json'

        run: |
          python scripts/update_data.py

      - name: Process data for site
        env:
          PYTHONPATH: scripts

        run: |
          python scripts/process_for_site.py
      
      - name: Run DVC pipelines
        env:
          PYTHONPATH: scripts
          GOOGLE_APPLICATION_CREDENTIALS: './credentials/serviceAccountKey.json'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: |
          dvc pull
          dvc repro

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data updates
          file_pattern: data docs
          github_token: ${{ secrets.GITHUB_TOKEN }}
