name: Microsite build

'on':
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Data Pipeline"]
    types:
      - completed
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '_config.js'
      - 'deno.json'
      - 'import_map.json'
      - '.github/workflows/deploy-site.yml'

# Cancel any in-flight jobs
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build the site
        uses: dringtech/lume-build@v1.1.0

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1