name: Data microsite build

'on':
  workflow_dispatch: {}
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '45 23 * * *'
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '_config.js'
      - 'deno.json'
      - 'import_map.json'
      - '.github/workflows/deploy-site.yml'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.5.0

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x

      - name: Build site
        run: |
          deno run -A https://deno.land/x/lume/ci.ts

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          build_dir: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
